### ISSUE TITLE
Self-managed Jira compatibility

### ISSUE THREAD

**Issue by Jason-Murray** [titouanmathis/alfred-jira-search#3]
Would it be possible to add self-managed Jira compatibility?

Where should I start looking, maybe I can put a PR in?

**Comment by titouanmathis** [comment]
Hi @Jason-Murray !

That would be a nice addition, I would be happy to help if you would like to open a PR.

I think the first thing to check is if the APIs for Jira Cloud and Jira Server offer the same endpoints.

If they share the same endpoints and auth configuration, it should be simple and switching the base URL for the request might do the trick.

If the APIs are too different, it might be more complex to implement.

**Comment by Jason-Murray** [comment]
@titouanmathis and I decided not to go forward with supporting both type of Jira server in this project due to some fundamental differences in the platforms.

I will however leave my branch with self-managed (self hosted) Jira compatibility here: https://github.com/Jason-Murray/alfred-jira-search

No guarantees it will be kept up to date or work as intended!
